title: Rage Gaming
tagline: Feel The Rage
author:
  name: The Rage Team
  email: hello@ragegaming.team

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Rage is a Nigerian-based eSports team that participates in the Call of Duty Mobile of PubG tournaments.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Theme-specific settings

minima:
  skin: dark

  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%Y-%m-%d"

# Generate social links in footer.
#
  social_links:
    - { platform: instagram,      user_url: "https://www.instagram.com/ragegamingaf/" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@RAGEGAMINGAF" }
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: github,         user_url: "https://github.com/therageteam" }
    - { platform: facebook,       user_url: "https://www.facebook.com/groups/officialragegaming" }
  #   - { platform: tiktok,         user_url: "https://www.tiktok.com/@ragegamingaf" }
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - _pages/about.md

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - README.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: false
